#@ load("@ytt:data", "data")
#@ load("@ytt:assert", "assert")
#@ load("@ytt:base64", "base64")
#@ load("@ytt:overlay", "overlay")
#@ load("_ytt.lib.yml", "labels")
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: postgres-postgresql-ha-additional-databases
  namespace: #@ data.values.namespace
  labels: #@ labels("additional-databases")
#@yaml/text-templated-strings
data:
  additional_databases.sh: |
    #!/bin/bash
    set -e
    (@ for db in data.values.postgres.additional_databases: @)
    (@ if len(db.name) == 0: @)
    (@  assert.fail("name of additional database cannot be empty") @)
    (@ end @)
    (@ if len(db.user) == 0: @)
    (@  assert.fail("user of additional database cannot be empty") @)
    (@ end @)
    (@ if len(db.password) == 0: @)
    (@  assert.fail("password of additional database cannot be empty") @)
    (@ end @)
    export DB_USERNAME=$(cat /docker-entrypoint-initdb.d/secret/(@= db.name @).username)
    export DB_PASSWORD=$(cat /docker-entrypoint-initdb.d/secret/(@= db.name @).password)

    cat > /tmp/setup_db.sql <<EOF
    CREATE DATABASE (@= db.name @);
    CREATE ROLE ${DB_USERNAME} LOGIN PASSWORD '${DB_PASSWORD}';
    GRANT ALL PRIVILEGES ON DATABASE (@= db.name @) TO ${DB_USERNAME};
    EOF

    export PGPASSWORD=$(cat /docker-entrypoint-initdb.d/secret/postgres.password)
    psql -v ON_ERROR_STOP=1 -U postgres -f /tmp/setup_db.sql
    psql -v ON_ERROR_STOP=1 -U postgres -d (@= db.name @) -c 'CREATE EXTENSION citext'

    rm -f /tmp/setup_db.sql
    (@ end @)
---
apiVersion: v1
kind: Secret
metadata:
  name: postgres-postgresql-ha-additional-database-credentials
  namespace: #@ data.values.namespace
  labels: #@ labels("additional-database-credentials")
#@yaml/text-templated-strings
data:
  #@ if len(data.values.postgres.database.password) == 0:
  #@  assert.fail("postgres.database.password cannot be empty")
  #@ end
  postgres.password: #@ base64.encode(data.values.postgres.database.password)
  #@ for db in data.values.postgres.additional_databases:
  #@ if len(db.name) == 0:
  #@  assert.fail("name of additional database cannot be empty")
  #@ end
  #@ if len(db.user) == 0:
  #@  assert.fail("user of additional database cannot be empty")
  #@ end
  #@ if len(db.password) == 0:
  #@  assert.fail("password of additional database cannot be empty")
  #@ end
  (@= db.name @).username: (@= base64.encode(db.user) @)
  (@= db.name @).password: (@= base64.encode(db.password) @)
  #@ end
